apply plugin: 'com.android.library'

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}

android {
    namespace "com.nightpost.widget"

    compileSdk getProperty("unity.compileSdkVersion") as int
    buildToolsVersion = getProperty("unity.buildToolsVersion")

    compileOptions {
        sourceCompatibility JavaVersion.valueOf(
            getProperty("unity.javaCompatabilityVersion")
        )

        targetCompatibility JavaVersion.valueOf(
            getProperty("unity.javaCompatabilityVersion")
        )
    }

    defaultConfig {
        minSdk getProperty("unity.minSdkVersion") as int
        targetSdk getProperty("unity.targetSdkVersion") as int
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}